import { StyleSheet, View } from 'react-native';

import { Icon } from '@/components/ui/icon';
import { PressableScale } from '@/components/ui/pressable-scale';
import { Text } from '@/components/ui/text';
import { Radius, Spacing } from '@/constants/theme';
import { formatTime } from '@/features/reminders/scheduler';
import { formatDateHeading } from '@/lib/date';
import { usePreferences, useT } from '@/features/settings/store';
import { useTheme } from '@/hooks/use-theme';
import type { TranslationKey } from '@/lib/i18n';
import type { CalendarEvent, ISODate, RepeatRule } from '@/types';

const REPEAT_LABELS: Record<RepeatRule, TranslationKey> = {
  none: 'calendar.repeatNone',
  daily: 'calendar.repeatDaily',
  weekly: 'calendar.repeatWeekly',
  monthly: 'calendar.repeatMonthly',
  yearly: 'calendar.repeatYearly',
};

export interface EventRowProps {
  event: CalendarEvent;
  /** True when this instance is generated by a repeat rule. */
  isRepeat?: boolean;
  /**
   * `rail` reads as a timeline — for a day's events in order on the calendar.
   * `chip` puts the time in a tinted block, for a short list out of context.
   */
  variant?: 'rail' | 'chip';
  /**
   * The day this occurrence falls on. Worth showing in a list that spans days;
   * omitted under a date heading, where every row shares it. Not the same as
   * `event.date`, which is where a repeating series started.
   */
  date?: ISODate;
  onPress: () => void;
}

export function EventRow({ event, isRepeat = false, variant = 'rail', date, onPress }: EventRowProps) {
  const theme = useTheme();
  const t = useT();
  const { preferences } = usePreferences();

  const repeats = isRepeat || event.repeat !== 'none';
  const hasReminder = event.reminderMinutesBefore !== undefined;
  // The description says the most, so it wins; the repeat rule fills in when
  // there isn't one, rather than leaving a bare icon with nothing beside it.
  const meta = event.description?.trim() || (repeats ? t(REPEAT_LABELS[event.repeat]) : undefined);
  const day = date
    ? formatDateHeading(date, preferences.language, {
        today: t('common.today'),
        yesterday: t('common.yesterday'),
      })
    : undefined;

  return (
    <PressableScale
      accessibilityRole="button"
      accessibilityLabel={event.title}
      onPress={onPress}
      scaleTo={0.99}
      style={styles.row}>
      {/* The rail leads, so a column of events reads as a timeline rather than
          as a list that happens to start with times. */}
      {variant === 'rail' ? (
        <View style={[styles.rail, { backgroundColor: theme.primary }]} />
      ) : null}

      <View
        style={[
          styles.timeColumn,
          variant === 'chip' && [styles.timeChip, { backgroundColor: theme.primarySoft }],
        ]}>
        {event.time ? (
          <Text
            variant="bodyStrong"
            tint={variant === 'chip' ? theme.primary : theme.text}
            align={variant === 'chip' ? 'center' : 'left'}
            numberOfLines={1}
            adjustsFontSizeToFit
            minimumFontScale={0.75}>
            {formatTime(event.time, preferences.language, preferences.timeFormat)}
          </Text>
        ) : (
          <Text
            variant="caption"
            color="textTertiary"
            align={variant === 'chip' ? 'center' : 'left'}
            numberOfLines={1}>
            {t('calendar.allDay')}
          </Text>
        )}
      </View>

      <View style={styles.body}>
        <Text variant="bodyStrong" numberOfLines={1}>
          {event.title}
        </Text>

        {day || repeats || meta || hasReminder ? (
          <View style={styles.meta}>
            {/* The day leads: in a list spanning several days it is what tells
                two otherwise identical entries apart. */}
            {day ? (
              <Text variant="captionStrong" color="textSecondary" numberOfLines={1}>
                {day}
              </Text>
            ) : null}

            {day && (repeats || meta) ? (
              <Text variant="caption" color="textTertiary">
                ·
              </Text>
            ) : null}

            {repeats ? <Icon name="repeat" size={12} color="textTertiary" /> : null}
            {meta ? (
              <Text variant="caption" color="textSecondary" numberOfLines={1} style={styles.metaText}>
                {meta}
              </Text>
            ) : null}
            {hasReminder ? <Icon name="notifications" size={12} color="warning" /> : null}
          </View>
        ) : null}
      </View>

      <Icon name="chevron-forward" size={16} color="textTertiary" />
    </PressableScale>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, paddingVertical: Spacing.md },
  timeColumn: { width: 72 },
  timeChip: {
    width: 76,
    paddingHorizontal: Spacing.xs,
    justifyContent: 'center',
    paddingVertical: Spacing.sm,
    borderRadius: Radius.sm,
  },
  rail: { width: 4, alignSelf: 'stretch', minHeight: 40, borderRadius: Radius.pill },
  body: { flex: 1, gap: 1 },
  meta: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginTop: 2 },
  metaText: { flexShrink: 1 },
});
