import { StyleSheet, View } from 'react-native';

import { Icon } from '@/components/ui/icon';
import { PressableScale } from '@/components/ui/pressable-scale';
import { Text } from '@/components/ui/text';
import { Radius, Spacing } from '@/constants/theme';
import { formatTime } from '@/features/reminders/scheduler';
import { usePreferences, useT } from '@/features/settings/store';
import { useTheme } from '@/hooks/use-theme';
import type { CalendarEvent } from '@/types';

export interface EventRowProps {
  event: CalendarEvent;
  /** True when this instance is generated by a repeat rule. */
  isRepeat?: boolean;
  onPress: () => void;
}

export function EventRow({ event, isRepeat = false, onPress }: EventRowProps) {
  const theme = useTheme();
  const t = useT();
  const { preferences } = usePreferences();

  return (
    <PressableScale
      accessibilityRole="button"
      accessibilityLabel={event.title}
      onPress={onPress}
      scaleTo={0.99}
      style={styles.row}>
      <View style={styles.timeColumn}>
        {event.time ? (
          <Text variant="captionStrong" numberOfLines={1}>
            {formatTime(event.time, preferences.language)}
          </Text>
        ) : (
          <Text variant="caption" color="textTertiary" numberOfLines={1}>
            {t('calendar.allDay')}
          </Text>
        )}
      </View>

      <View style={[styles.rail, { backgroundColor: theme.primary }]} />

      <View style={styles.body}>
        <Text variant="bodyStrong" numberOfLines={1}>
          {event.title}
        </Text>
        {event.description ? (
          <Text variant="caption" color="textSecondary" numberOfLines={1}>
            {event.description}
          </Text>
        ) : null}

        <View style={styles.meta}>
          {event.reminderMinutesBefore !== undefined ? (
            <Icon name="notifications-outline" size={12} color="textTertiary" />
          ) : null}
          {isRepeat || event.repeat !== 'none' ? (
            <Icon name="repeat" size={12} color="textTertiary" />
          ) : null}
        </View>
      </View>
    </PressableScale>
  );
}

const styles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'stretch', gap: Spacing.md, paddingVertical: Spacing.md },
  timeColumn: { width: 62, paddingTop: 1 },
  rail: { width: 3, borderRadius: Radius.pill },
  body: { flex: 1, gap: 1 },
  meta: { flexDirection: 'row', gap: Spacing.sm, marginTop: 2 },
});
